### ISSUE TITLE
new version not supported (bought G5 Next this year - 2020)

### ISSUE THREAD

**Issue by viotemp1** [lynix/aerotools-ng#41]
Hello,

Can you gous help me to make it working for the last firmware version. Not sure which one I have, I have only Linux. I bought the pump few days ago.

Here you have the messages:

sudo ./aerocli
WARNING: unsupported firmware version
----------- System -----------
Time:      2009-01-01 02:00:00
Uptime:           00d 00:00:00
CPU Temp:              0.00 °C
---- Temperature Sensors -----
Sensor  1:             0.00 °C
Sensor  2:             0.00 °C
Sensor  3:             0.00 °C
Sensor  4:             0.00 °C
Sensor  5:             0.00 °C
Sensor  6:             0.00 °C
Sensor  7:             0.00 °C
Sensor  8:             0.00 °C
Sensor  9:             0.00 °C
Sensor 10:             0.00 °C
Sensor 11:             0.00 °C
Sensor 12:             0.00 °C
Sensor 13:             0.00 °C
Sensor 14:             0.00 °C
Sensor 15:             0.00 °C
Sensor 16:             0.00 °C
------------ Fans ------------
Fan  1:      0rpm @   0%  0 °C
Fan  2:      0rpm @   0%  0 °C
Fan  3:      0rpm @   0%  0 °C
Fan  4:      0rpm @   0%  0 °C
Fan  5:      0rpm @   0%  0 °C
Fan  6:      0rpm @   0%  0 °C
Fan  7:      0rpm @   0%  0 °C
Fan  8:      0rpm @   0%  0 °C
Fan  9:      0rpm @   0%  0 °C
Fan 10:      0rpm @   0%  0 °C
Fan 11:      0rpm @   0%  0 °C
Fan 12:      0rpm @   0%  0 °C
-------- Flow Sensors --------
------- Liquid Levels --------

Regards,
Viorel

**Comment by lynix** [comment]
Well, I'm sorry, but this project only covers the Aquaero5, no pumps or other equipment.

Apart from that I'm afraid there's nothing I can do for you. I don't own any AquaComputer equipment anymore since 2015 so I cannot reverse-engineer or test anything. I'll be setting this project to _archived_ to make it clear that it has been discontinued.

Best wishes and good luck with getting G5 on Linux!
